### ISSUE TITLE
LibSass doe not support /attr/ reference combinator

### ISSUE THREAD

**Issue by peterblazejewicz** [sass-compatibility/sass-compatibility.github.io#34]
Current version of LibSass does not support selectors like:
```css
body /deep/ .library {
  color: blue;
}
```
https://github.com/sass/libsass/issues/452

I can find a reference to /attr/ support in Sass 3.2:
https://github.com/sass/sass/releases/tag/3.2.0
http://sass-lang.com/documentation/file.SASS_CHANGELOG.html
